freebsd_task:
  name: FreeBSD
  freebsd_instance:
    matrix:
      image_family: freebsd-14-3
  env:
    matrix:
      LLVM_VERSION: 12
      LLVM_VERSION: 13
      # LLVM_VERSION: 14
      LLVM_VERSION: 15
      LLVM_VERSION: 16
      LLVM_VERSION: 17
      LLVM_VERSION: 18
  install_script: pkg install -y bash coreutils cmake gmake llvm$LLVM_VERSION
  script: |
    export CC=cc
    bash travis.sh
