freebsd_task:
  name: FreeBSD
  freebsd_instance:
    matrix:
      image_family: freebsd-14-0
  env:
    matrix:
      LLVM_VERSION: 11
      LLVM_VERSION: 12
      LLVM_VERSION: 13
      # LLVM_VERSION: 14
      LLVM_VERSION: 15
      LLVM_VERSION: 16
      LLVM_VERSION: 17
      LLVM_VERSION: 18
  install_script: pkg install -y bash coreutils cmake gmake llvm$LLVM_VERSION
  script: |
    export CC=cc
    bash travis.sh

arm_task:
  name: Linux AArch64
  arm_container:
    image: ubuntu:18.04
  env:
    llvm: 11.1.0
    cuda: 0
    variant: prebuilt
    test: 1
    threads: 2
  script: |
    ./docker/install_script.sh
