ARG release=18.04

FROM ubuntu:$release

ARG llvm=6.0
ARG lua=luajit
ARG cuda=0
ARG variant=package
ARG test=1
ARG threads=4

ENV DEBIAN_FRONTEND noninteractive
ENV CI 1 # skip CUDA tests

COPY . /terra

RUN cd /terra && ./docker/install_script.sh
