ARG release=16.04

FROM ubuntu:$release

ENV DEBIAN_FRONTEND noninteractive

COPY . /terra_install

RUN cat /etc/lsb-release && \
    apt-get update -qq && \
    apt-get install -qq build-essential libedit-dev && \
    cd /terra_install/share/terra/tests && \
    /terra_install/bin/terra ./run
