include(FindPackageHandleStandardArgs)

set(LUAJIT_VERSION_BASE 2.0)
set(LUAJIT_VERSION_EXTRA .5)
set(LUAJIT_BASENAME "LuaJIT-${LUAJIT_VERSION_BASE}${LUAJIT_VERSION_EXTRA}")
set(LUAJIT_URL "https://luajit.org/download/${LUAJIT_BASENAME}.tar.gz")
set(LUAJIT_TAR "${PROJECT_BINARY_DIR}/${LUAJIT_BASENAME}.tar.gz")
set(LUAJIT_DIR "${PROJECT_BINARY_DIR}/${LUAJIT_BASENAME}")
set(LUAJIT_INCLUDE_DIR "${PROJECT_BINARY_DIR}/include/luajit-${LUAJIT_VERSION_BASE}")
set(LUAJIT_HEADER_BASENAMES lua.h lualib.h lauxlib.h luaconf.h)
set(LUAJIT_LIBRARY "${PROJECT_BINARY_DIR}/lib/libluajit-5.1.a")
set(LUAJIT_EXECUTABLE "${PROJECT_BINARY_DIR}/bin/luajit-${LUAJIT_VERSION_BASE}${LUAJIT_VERSION_EXTRA}")

file(DOWNLOAD "${LUAJIT_URL}" "${LUAJIT_TAR}")

add_custom_command(
  OUTPUT ${LUAJIT_DIR}
  DEPENDS ${LUAJIT_TAR}
  COMMAND ${CMAKE_COMMAND} -E tar xzf ${LUAJIT_TAR}
  WORKING_DIRECTORY ${PROJECT_BINARY_DIR}
)

foreach(LUAJIT_HEADER ${LUAJIT_HEADER_BASENAMES})
  list(APPEND LUAJIT_INSTALL_HEADERS "${LUAJIT_INCLUDE_DIR}/${LUAJIT_HEADER}")
endforeach()

add_custom_command(
  OUTPUT ${LUAJIT_LIBRARY} ${LUAJIT_EXECUTABLE} ${LUAJIT_INSTALL_HEADERS}
  DEPENDS ${LUAJIT_DIR}
  COMMAND make install "PREFIX=${PROJECT_BINARY_DIR}" "CC=${CMAKE_C_COMPILER}" "STATIC_CC=${CMAKE_C_COMPILER} -fPIC"
  WORKING_DIRECTORY "${LUAJIT_DIR}"
)

foreach(LUAJIT_HEADER ${LUAJIT_HEADER_BASENAMES})
  list(APPEND LUAJIT_HEADERS "${PROJECT_SOURCE_DIR}/release/include/terra/${LUAJIT_HEADER}")
endforeach()

foreach(LUAJIT_HEADER ${LUAJIT_HEADER_BASENAMES})
  add_custom_command(
    OUTPUT "${PROJECT_SOURCE_DIR}/release/include/terra/${LUAJIT_HEADER}"
    DEPENDS "${LUAJIT_INCLUDE_DIR}/${LUAJIT_HEADER}"
    COMMAND ${CMAKE_COMMAND} -E copy "${LUAJIT_INCLUDE_DIR}/${LUAJIT_HEADER}" "${PROJECT_SOURCE_DIR}/release/include/terra/"
  )
endforeach()

add_custom_target(
  LuaJIT
  DEPENDS ${LUAJIT_LIBRARY} ${LUAJIT_EXECUTABLE} ${LUAJIT_HEADERS}
)

set(LUAJIT_INCLUDE_DIRS ${LUAJIT_INCLUDE_DIR})
set(LUAJIT_LIBRARIES ${LUAJIT_LIBRARY})
mark_as_advanced(
  LUAJIT_VERSION_BASE
  LUAJIT_VERSION_EXTRA
  LUAJIT_BASENAME
  LUAJIT_URL
  LUAJIT_TAR
  LUAJIT_INCLUDE_DIR
  LUAJIT_LIBRARY
)
